from typing import Protocol

from app.locales import Locale
from app.schemas.survey import (
    DialogMessage,
    RespondentConfig,
    RespondentProfile,
    SurveyQuestion,
)


class SimulationEngine(Protocol):
    async def wait_before_question(self) -> None: ...
    async def wait_before_answer(self) -> None: ...
    def generate_respondents(self, configs: list[RespondentConfig], locale: Locale) -> list[RespondentProfile]: ...
    def generate_answer(self, respondent: RespondentProfile, question: SurveyQuestion, locale: Locale) -> DialogMessage: ...
    def termination_message(self, locale: Locale) -> DialogMessage: ...
    def termination_reason(self, locale: Locale, actor: str, low_quality: bool = False) -> str: ...
    def respondent_should_terminate(self, previous_dialog: list[DialogMessage]) -> bool: ...
    def response_is_low_quality(self, previous_dialog: list[DialogMessage]) -> bool: ...
    def interviewer_should_terminate(self, dialog: list[DialogMessage], low_quality: bool) -> bool: ...
